### ISSUE TITLE
[Bug] Nil pointer on querier

### ISSUE THREAD

**Issue by dmicheneau** [orange-cloudavenue/cloudavenue-sdk-go#100]
nil pointer when argument doesn't exist

```
go run . get vdc --name toto
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/orange-cloudavenue/cloudavenue-sdk-go/v1.(*Get).VDC(...)
        /Users/micheneaudavid/go/pkg/mod/github.com/orange-cloudavenue/cloudavenue-sdk-go@v0.10.0/v1/querier.go:115
github.com/orange-cloudavenue/cloudavenue-cli/cmd.init.func13(0x102463e00, {0x10141dd60?, 0x4?, 0x10141dc7c?})
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/cmd/get_vdc.go:40 +0x880
github.com/spf13/cobra.(*Command).execute(0x102463e00, {0x140005ae3c0, 0x2, 0x2})
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1024640e0)
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/micheneaudavid/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/orange-cloudavenue/cloudavenue-cli/cmd.Execute()
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/cmd/root.go:26 +0x68
main.main()
        /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/cloudavenue-cli/main.go:18 +0x20
exit status 2
```

**Comment by dmicheneau** [comment]
Need to check the result before to return the array, because sometimes the can be empty like the example above.

```
// VDC get a vdc informations by name
func (q *Get) VDC(vdcName string) (*types.QueryResultOrgVdcRecordType, error) {
	r, err := queryGet(typeVDC, vdcName)
	return r.Results.OrgVdcRecord[0], err
}
```
